-- ChangeLake Phase 6 / G7: dt-scoped DWD repair FROM MySQL snapshot (bypass CDC).
-- Placeholders: __DT__  (YYYY-MM-DD)
-- Mode: batch. PK table → DELETE rows for dt, then INSERT VALUES generated by scripts/backfill.sh.
-- coupon_amount stays NULL; net_amount = amount. channel from MySQL if present else NULL.
-- Honest: demo partition-scoped logic (logical dt = DATE(order_ts)), not a general orchestrator.

SET 'pipeline.name' = 'changelake-backfill-dwd-__DT__';
SET 'execution.runtime-mode' = 'batch';
SET 'parallelism.default' = '1';
SET 'sql-client.execution.result-mode' = 'tableau';

CREATE CATALOG paimon WITH (
  'type' = 'paimon',
  'warehouse' = 's3://changelake/warehouse',
  's3.endpoint' = 'http://minio:9000',
  's3.access-key' = 'minioadmin',
  's3.secret-key' = 'minioadmin',
  's3.path.style.access' = 'true'
);

USE CATALOG paimon;
CREATE DATABASE IF NOT EXISTS dwd;

CREATE TABLE IF NOT EXISTS dwd.dwd_orders (
  order_id BIGINT,
  user_id BIGINT,
  status STRING,
  amount DECIMAL(12, 2),
  channel STRING,
  coupon_amount DECIMAL(12, 2),
  net_amount DECIMAL(12, 2),
  order_ts TIMESTAMP(0),
  updated_at TIMESTAMP(0),
  PRIMARY KEY (order_id) NOT ENFORCED
) WITH (
  'bucket' = '1',
  'changelog-producer' = 'input',
  'merge-engine' = 'deduplicate'
);

-- Replace logical partition: remove all DWD rows whose order_ts falls on __DT__
DELETE FROM dwd.dwd_orders WHERE CAST(order_ts AS DATE) = DATE '__DT__';

-- __DWD_VALUES_INSERT__
